# .github/workflows/build.yml

name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 'Building...'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: MatNoble/matnoble.github.io
        DEPLOY_BRANCH: build
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        TZ: Asia/Shanghai

    - name: 'Upload Algolia'
      uses: iChochy/Algolia-Upload-Records@main
      # 设置环境变量利用secrets
      env:
        APPLICATION_ID: ${{secrets.APPLICATION_ID}}
        ADMIN_API_KEY: ${{secrets.ADMIN_API_KEY}}
        INDEX_NAME: ${{secrets.INDEX_NAME}}
        FILE_PATH: ./algolia.json
