# .github/workflows/build.yml

name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.0'

      - name: Install dependencies
        run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          TZ: Asia/Shanghai
          DEPLOY_REPO: MatNoble/matnoble.github.io
          DEPLOY_BRANCH: master
          PERSONAL_TOKEN: ${{ secrets.DEPLOY_KEY }}
        run: |
          cd ./public && git init
          git config user.name "MatNoble"
          git config user.email "hustmatnoble@gmail.com"
          git add .
          git commit -m "Automated Deployment @ $(date '+%Y-%m-%d %H:%M:%S') ${TZ}"
          git push --force --quiet "https://$PERSONAL_TOKEN@github.com/$DEPLOY_REPO" master:$DEPLOY_BRANCH